require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

# plugin 'cocoapods-art', :sources => [
#     'whoyou-cocoapods-local',
#     'cocoapods-remote-finger',
#     'cocoapods-remote-face'
# ]

target 'MrpMoneyInStore' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'WatermelonDB', :path => '../node_modules/@nozbe/watermelondb'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true

  target 'AwesomeTSProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#   use_flipper!()
#
#   post_install do |installer|
#     react_native_post_install(installer)
#     __apply_Xcode_12_5_M1_post_install_workaround(installer)
#   end
    use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
      post_install do |installer|
        flipper_post_install(installer)
        installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
              config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
              config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
            end
        end
      end
end
